// Encoder is the clean-room erasure-coding primitive used by the
// Phase 3 local-DC write path.
//
// The profile types in profile.go describe the (k + m, StripeSize)
// shape of a Reed-Solomon code; this file provides the actual
// stripe / shard / reconstruct operations on top of the MIT-licensed
// klauspost/reedsolomon codec.
//
// License note: no AGPL code is referenced here. Storj's
// eestream / infectious packages were consulted purely for their
// public API shape (Encode → shards, Reconstruct → data) — the
// striping, padding, and shard-size accounting below are original.

package erasure_coding

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"io"

	"github.com/klauspost/reedsolomon"
)

// ShardKind identifies whether a shard carries data or parity bytes.
type ShardKind int

const (
	// ShardKindData is a shard that directly backs a slice of the
	// original plaintext.
	ShardKindData ShardKind = 0

	// ShardKindParity is a shard generated by the Reed-Solomon
	// encoder and useful only for reconstruction.
	ShardKindParity ShardKind = 1
)

func (k ShardKind) String() string {
	switch k {
	case ShardKindData:
		return "data"
	case ShardKindParity:
		return "parity"
	}
	return "unknown"
}

// Shard is the unit of ciphertext the gateway writes to a backend.
type Shard struct {
	// StripeIndex is the 0-based stripe this shard belongs to.
	StripeIndex int
	// ShardIndex is the 0-based index within (DataShards + ParityShards).
	ShardIndex int
	// Kind is ShardKindData for shards [0 .. k-1] or
	// ShardKindParity for shards [k .. k+m-1].
	Kind ShardKind
	// Bytes is the shard payload. Length is equal to the stripe's
	// ShardSize (see Encoder.ShardSize) — every shard in a stripe
	// is the same size, including any padding.
	Bytes []byte
}

// Encoder produces (and reconstructs) Shards for a specific profile.
//
// Encoders are safe for concurrent use: the underlying RS codec is
// stateless, and every Encode / Reconstruct call allocates its own
// working buffers.
type Encoder struct {
	profile ErasureCodingProfile
	codec   reedsolomon.Encoder

	// shardSize is the per-shard byte count for a full stripe. It is
	// derived once from StripeSize / DataShards (rounded up so every
	// shard is the same size) and reused for every Encode call.
	shardSize int
}

// NewEncoder returns an Encoder bound to the given profile.
func NewEncoder(p ErasureCodingProfile) (*Encoder, error) {
	if err := p.Validate(); err != nil {
		return nil, err
	}
	codec, err := reedsolomon.New(p.DataShards, p.ParityShards)
	if err != nil {
		return nil, fmt.Errorf("erasure_coding: build rs codec: %w", err)
	}
	shardSize := int((p.StripeSize + int64(p.DataShards) - 1) / int64(p.DataShards))
	return &Encoder{
		profile:   p,
		codec:     codec,
		shardSize: shardSize,
	}, nil
}

// Profile returns the encoder's profile.
func (e *Encoder) Profile() ErasureCodingProfile {
	return e.profile
}

// ShardSize returns the number of bytes in each shard. All shards —
// data and parity — are the same size.
func (e *Encoder) ShardSize() int {
	return e.shardSize
}

// StripeLength returns ShardSize * DataShards, which is the number of
// plaintext bytes one stripe represents before padding. It is the
// effective stripe size used internally; the profile's StripeSize is
// rounded up to this when it is not already a multiple of DataShards.
func (e *Encoder) StripeLength() int {
	return e.shardSize * e.profile.DataShards
}

// ObjectHeader is the small preamble the encoder prepends to the
// first data shard so the decoder knows how much of the last stripe
// is padding. It is 8 bytes: a big-endian unsigned 64-bit plaintext
// length.
const objectHeaderSize = 8

// Encode splits body into stripes, encodes each stripe into
// (k + m) shards, and returns the shards in stripe-major order:
//
//	[stripe0 shard0, stripe0 shard1, ..., stripe0 shard(k+m-1),
//	 stripe1 shard0, ..., stripeN shard(k+m-1)]
//
// The first 8 bytes of stripe 0's first data shard are a big-endian
// length prefix so Decode can trim the final stripe's padding.
func (e *Encoder) Encode(body []byte) ([]Shard, error) {
	if body == nil {
		body = []byte{}
	}
	plaintextLen := len(body)
	header := make([]byte, objectHeaderSize)
	binary.BigEndian.PutUint64(header, uint64(plaintextLen))
	framed := make([]byte, 0, objectHeaderSize+plaintextLen)
	framed = append(framed, header...)
	framed = append(framed, body...)

	stripeLen := e.StripeLength()
	numStripes := (len(framed) + stripeLen - 1) / stripeLen
	if numStripes == 0 {
		numStripes = 1
	}
	total := numStripes * e.profile.TotalShards()
	out := make([]Shard, 0, total)

	for s := 0; s < numStripes; s++ {
		start := s * stripeLen
		end := start + stripeLen
		if end > len(framed) {
			end = len(framed)
		}
		stripe := make([]byte, stripeLen)
		copy(stripe, framed[start:end])

		shards := make([][]byte, e.profile.TotalShards())
		for i := 0; i < e.profile.DataShards; i++ {
			shards[i] = stripe[i*e.shardSize : (i+1)*e.shardSize]
		}
		for i := e.profile.DataShards; i < e.profile.TotalShards(); i++ {
			shards[i] = make([]byte, e.shardSize)
		}
		if err := e.codec.Encode(shards); err != nil {
			return nil, fmt.Errorf("erasure_coding: rs encode stripe %d: %w", s, err)
		}
		for i, shard := range shards {
			kind := ShardKindData
			if i >= e.profile.DataShards {
				kind = ShardKindParity
			}
			b := make([]byte, e.shardSize)
			copy(b, shard)
			out = append(out, Shard{
				StripeIndex: s,
				ShardIndex:  i,
				Kind:        kind,
				Bytes:       b,
			})
		}
	}
	return out, nil
}

// Decode rebuilds the original plaintext from a set of Shards. Missing
// shards may be represented either by omission from the slice or by
// passing a Shard with a nil / empty Bytes field. Decode tolerates up
// to ParityShards losses per stripe.
//
// The returned byte slice is the plaintext passed to Encode (without
// the length-prefix header).
func (e *Encoder) Decode(shards []Shard) ([]byte, error) {
	if len(shards) == 0 {
		return nil, errors.New("erasure_coding: no shards supplied")
	}
	total := e.profile.TotalShards()

	// Group shards by stripe, preserving order by ShardIndex.
	stripes := map[int][][]byte{}
	for _, sh := range shards {
		if sh.ShardIndex < 0 || sh.ShardIndex >= total {
			return nil, fmt.Errorf("erasure_coding: shard index %d out of range [0,%d)", sh.ShardIndex, total)
		}
		stripe, ok := stripes[sh.StripeIndex]
		if !ok {
			stripe = make([][]byte, total)
			stripes[sh.StripeIndex] = stripe
		}
		if len(sh.Bytes) == 0 {
			continue
		}
		if len(sh.Bytes) != e.shardSize {
			return nil, fmt.Errorf("erasure_coding: stripe %d shard %d has size %d, want %d",
				sh.StripeIndex, sh.ShardIndex, len(sh.Bytes), e.shardSize)
		}
		b := make([]byte, e.shardSize)
		copy(b, sh.Bytes)
		stripe[sh.ShardIndex] = b
	}

	numStripes := len(stripes)
	framed := make([]byte, 0, numStripes*e.StripeLength())
	for s := 0; s < numStripes; s++ {
		stripe, ok := stripes[s]
		if !ok {
			return nil, fmt.Errorf("erasure_coding: missing stripe %d", s)
		}
		present := 0
		for _, shard := range stripe {
			if len(shard) != 0 {
				present++
			}
		}
		if present < e.profile.DataShards {
			return nil, fmt.Errorf(
				"erasure_coding: stripe %d only has %d shards, need at least %d",
				s, present, e.profile.DataShards)
		}
		if present < total {
			if err := e.codec.ReconstructData(stripe); err != nil {
				return nil, fmt.Errorf("erasure_coding: reconstruct stripe %d: %w", s, err)
			}
		}
		for i := 0; i < e.profile.DataShards; i++ {
			framed = append(framed, stripe[i]...)
		}
	}
	if len(framed) < objectHeaderSize {
		return nil, errors.New("erasure_coding: decoded output is too short to contain length header")
	}
	plaintextLen := binary.BigEndian.Uint64(framed[:objectHeaderSize])
	end := uint64(objectHeaderSize) + plaintextLen
	if end > uint64(len(framed)) {
		return nil, fmt.Errorf(
			"erasure_coding: declared plaintext length %d exceeds decoded buffer of %d bytes",
			plaintextLen, len(framed)-objectHeaderSize)
	}
	return framed[objectHeaderSize:end], nil
}

// DecodeReader is a streaming variant of Decode that reads each
// shard's body from an io.Reader. It is used by the GET path which
// streams shards from backend providers.
//
// shardReaders is indexed by (stripeIndex, shardIndex). Nil entries
// indicate missing shards; Decode must be able to reconstruct them
// from the surviving k shards per stripe.
func (e *Encoder) DecodeReader(numStripes int, shardReaders [][]io.Reader) ([]byte, error) {
	if numStripes <= 0 {
		return nil, errors.New("erasure_coding: numStripes must be positive")
	}
	if len(shardReaders) != numStripes {
		return nil, fmt.Errorf("erasure_coding: shardReaders has %d entries, want %d", len(shardReaders), numStripes)
	}
	shards := make([]Shard, 0, numStripes*e.profile.TotalShards())
	for s := 0; s < numStripes; s++ {
		if len(shardReaders[s]) != e.profile.TotalShards() {
			return nil, fmt.Errorf(
				"erasure_coding: stripe %d has %d shard slots, want %d",
				s, len(shardReaders[s]), e.profile.TotalShards())
		}
		for i, r := range shardReaders[s] {
			var body []byte
			if r != nil {
				buf := bytes.Buffer{}
				if _, err := io.Copy(&buf, r); err != nil {
					return nil, fmt.Errorf("erasure_coding: read stripe %d shard %d: %w", s, i, err)
				}
				body = buf.Bytes()
			}
			kind := ShardKindData
			if i >= e.profile.DataShards {
				kind = ShardKindParity
			}
			shards = append(shards, Shard{
				StripeIndex: s,
				ShardIndex:  i,
				Kind:        kind,
				Bytes:       body,
			})
		}
	}
	return e.Decode(shards)
}
